In [6]:
import numpy as np

In [8]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [9]:
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [11]:
a1 = np.arange(12).reshape(3,4)

In [28]:
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
a1 == 12

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [30]:
a2 = np.arange(12,24).reshape(3,4)

In [26]:
print(a2)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [31]:
a1 ** a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]], dtype=int32)

In [32]:
a1 = np.random.random((3,3))
print(a1)

[[0.10831515 0.19309353 0.21576359]
 [0.71136051 0.85772832 0.15945713]
 [0.47564643 0.39948376 0.86123548]]


In [33]:
a1 = np.round(a1*100)
print(a1)

[[11. 19. 22.]
 [71. 86. 16.]
 [48. 40. 86.]]


In [34]:
np.prod(a1, axis=0)

array([37488., 65360., 30272.])

In [35]:
np.prod(a1, axis=1)

array([  4598.,  97696., 165120.])

In [41]:
a1 = np.arange(12).reshape(2,2,3)
print(a1)


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [42]:
np.sin(a1)

array([[[ 0.        ,  0.84147098,  0.90929743],
        [ 0.14112001, -0.7568025 , -0.95892427]],

       [[-0.2794155 ,  0.6569866 ,  0.98935825],
        [ 0.41211849, -0.54402111, -0.99999021]]])

In [45]:
np.cos(a1)

array([[[ 1.        ,  0.54030231, -0.41614684],
        [-0.9899925 , -0.65364362,  0.28366219]],

       [[ 0.96017029,  0.75390225, -0.14550003],
        [-0.91113026, -0.83907153,  0.0044257 ]]])

In [46]:
np.tan(a1)

array([[[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00],
        [-1.42546543e-01,  1.15782128e+00, -3.38051501e+00]],

       [[-2.91006191e-01,  8.71447983e-01, -6.79971146e+00],
        [-4.52315659e-01,  6.48360827e-01, -2.25950846e+02]]])

In [18]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [6]:
a.ndim

2

In [7]:
a.dtype.name

'int32'

In [8]:
a.itemsize

4

In [9]:
a.size

15

In [10]:
type(a)

numpy.ndarray

In [12]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [13]:
type(b)

numpy.ndarray

In [19]:
b.dtype

dtype('int32')

In [20]:
a.dtype

dtype('int32')

In [21]:
b = np.array([(1.5,2,3),(3,4,5)])
b

array([[1.5, 2. , 3. ],
       [3. , 4. , 5. ]])

In [25]:
c = np.array([ [1,2],[3,4] ], dtype = complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones((3,4,5), dtype = np.int16)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [33]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
np.arange(20,50,5)

array([20, 25, 30, 35, 40, 45])

In [39]:
from numpy import pi

In [41]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [49]:
a=np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [54]:
b=np.arange(16).reshape(2,2,4)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [55]:
print(np.arange(10000))


[   0    1    2 ... 9997 9998 9999]


In [57]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]
